# Generated by Django 4.1.3 on 2023-01-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('repository', models.CharField(max_length=100)),
                ('dbadmin', models.CharField(max_length=100)),
                ('dbpassword', models.CharField(max_length=228)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
