# Generated by Django 4.1.3 on 2023-01-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
