# Generated by Django 4.1.3 on 2023-01-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_docker_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='subdomain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
