# Generated by Django 3.2.12 on 2023-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20230425_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_mysql',
            field=models.BooleanField(default=False),
        ),
    ]
