# Generated by Django 3.2.12 on 2023-04-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_service_has_mysql'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='has_mysql',
            new_name='hasMysql',
        ),
    ]
