# Generated by Django 4.1.3 on 2022-12-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('docker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.docker')),
            ],
        ),
        migrations.AddField(
            model_name='docker',
            name='web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.web'),
        ),
    ]
