# Generated by Django 4.1.3 on 2023-01-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='docker',
        ),
        migrations.DeleteModel(
            name='Docker',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Web',
        ),
    ]
